{% set name = "mpl_plotter" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d878c581380ce166e1567b380c626cdbc5bd75fc7ec2a2ab1286093e0140f69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.19.5
    - pandas >=1.1.5
    - pyqt
    - python >=3.6
    - toml >=0.10.1

test:
  source_files:
    - tests
  imports:
    - mpl_plotter
  commands:
    - pip check
    # Skip running test suite for now as it require non-headless QT
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/alopezrivera/mpl_plotter
  summary: Publication-quality data representation library based on Matplotlib.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
