{% set name = "mpl_plotter" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b9998569c47c4a9452742b5cedfe6d6f6a296c7e50128081d3fb0a6b23f0abd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.19.5
    - pandas >=1.1.5
    - pyqt
    - python >=3.6
    - toml >=0.10.1

test:
  source_files:
    - tests
  imports:
    - mpl_plotter
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/alopezrivera/mpl_plotter
  summary: Publication-quality data representation library based on Matplotlib.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
