{% set name = "mpl_plotter" %}
{% set version = "5.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ca333ffde47213b8310a3f26b3643ca858fffbf0608c0b576e6e5ba699b9fee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.19.5
    - pandas >=1.1.5
    - pyqt
    - python >={{ python_min }}
    - toml >=0.10.1

test:
  source_files:
    - tests
  imports:
    - mpl_plotter
  commands:
    - pip check
    # Skip running test suite for now as it require non-headless QT
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/alopezrivera/mpl_plotter
  summary: Publication-quality data representation library based on Matplotlib.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
