{% set name = "mpl_plotter" %}
{% set version = "5.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff5bf1642302abbd90e7952cb30cf25c0e198aecfed20607d436971f40972209

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.19.5
    - pandas >=1.1.5
    - pyqt
    - python >=3.6
    - toml >=0.10.1

test:
  imports:
    - mpl_plotter

about:
  home: https://github.com/alopezrivera/mpl_plotter
  summary: Publication-quality data representation library based on Matplotlib.
  license: GPL-3.0-or-later
  # Will PR upstream to pacakge in license
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
